import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
padding.x = 10
padding.y = 10

[font]
size = 22
normal.family = "JetBrainsMonoNL Nerd Font Mono"
offset.x = 0 
offset.y = 1 

# [font.offset]
# x = 0 
# y = 1 
#
# [font.normal]
# family = "JetBrainsMonoNL Nerd Font Mono"

# [window.padding]
# x = 8 
# y = 8
